class ChatMessage {
  final String id;
  final String placeId;
  final String userId;
  final String userName;
  final String text;
  final DateTime sentAt;
  final String? userAvatarColor;

  const ChatMessage({
    required this.id,
    required this.placeId,
    required this.userId,
    required this.userName,
    required this.text,
    required this.sentAt,
    this.userAvatarColor,
  });

  factory ChatMessage.fromJson(Map<String, dynamic> json) => ChatMessage(
    id: json['id'].toString(),
    placeId: json['place_id'] as String,
    userId: json['user_id'].toString(),
    userName: (json['user_name'] as String?) ?? 'Explorer',
    text: (json['message'] ?? json['text'] ?? '') as String,
    sentAt: DateTime.parse(json['sent_at'] as String),
    userAvatarColor: json['user_avatar_color'] as String?,
  );

  /// Row for `public.place_chat`. `id` and `sent_at` are generated by the
  /// database; `user_id` must be the signed-in Supabase user's uuid (RLS
  /// rejects anything else).
  Map<String, dynamic> toJson() => {
    'place_id': placeId,
    'user_id': userId,
    'user_name': userName,
    'message': text,
  };

  ChatMessage copyWith({String? text}) => ChatMessage(
    id: id,
    placeId: placeId,
    userId: userId,
    userName: userName,
    text: text ?? this.text,
    sentAt: sentAt,
    userAvatarColor: userAvatarColor,
  );
}
